- name: Kafka Plaintext Configuration
  hosts: all_nodes
  vars_files:
    - variables/secrets.yaml
    - variables/env.yaml
  vars:
    ansible_ssh_pass: "{{ ssh_password }}"
  tasks:
    - name: Copy server.properties file to kafka servers
      template:
        src: templates/server.properties.plaintext.j2
        dest: "{{ KAFKA_SERVER_CONFIG }}"

    - name: Copy kafka.service systemd file to servers
      template:
        src: templates/kafka.service.j2
        dest: "{{ KAFKA_SERVICE_PATH }}"

    - name: Set Kafka node.id
      lineinfile:
        path: /opt/kafka/config/server.properties
        regexp: "^node.id="
        line: "node.id={{ node_id }}"

    - name: Generate Log Storage
      shell: "{{ KAFKA_DIR }}/bin/kafka-storage.sh format -t {{ KAFKA_CLUSTER_ID }} -c {{ KAFKA_SERVER_CONFIG }}"

    - name: Restart service kafka also issue daemon-reload to pick up config changes
      ansible.builtin.systemd_service:
        state: restarted
        daemon_reload: true
        name: kafka

    - name: Wait for 10 seconds for starting kafka cluster
      pause:
        seconds: 10

    - name: Get Kafka Cluster Status
      shell: "{{ KAFKA_DIR }}/bin/kafka-metadata-quorum.sh --bootstrap-controller {{ inventory_hostname }}:{{ CONTROLLER_PORT }} describe --status"
      when: ('controller' in group_names)
      register: kafka_cluster_output

    - name: Show Kafka Cluster Status
      debug:
        var: kafka_cluster_output
