- name: Create user and give ACL
  hosts: all
  vars_files:
    - variables/secrets.yaml
    - variables/env.yaml
  vars:
    ansible_ssh_pass: "{{ ssh_password }}"
    ansible_become_pass: "{{ ssh_password }}"
  tasks:

    - name: Copy acl script file to server
      template:
        src: templates/create-acl.sh.j2
        dest: "{{ KAFKA_DIR }}/create-acl.sh"
        mode: "0755"
      when: inventory_hostname == groups['brokers'][0]

    - name: Run script create user and give acl
      shell: bash "{{ KAFKA_DIR }}/create-acl.sh"
      register: script_output
      when: inventory_hostname == groups['brokers'][0]

    - name: Show script result
      debug:
        var: script_output